
import { Language, ContentData } from './types';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'am', name: 'አማርኛ', flag: '🇪🇹' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'العربية', flag: '🇦🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
];

export const DICTIONARY: Record<Language, ContentData> = {
  en: {
    navHome: "Home",
    navAbout: "About Us",
    navRooms: "Rooms",
    navDining: "Restaurants & Lounge",
    navSpa: "Spa & Massage",
    navFitness: "Fitness",
    heroTitle: "Elegance in Motion, Wellness in Spirit",
    heroSub: "Experience the pinnacle of luxury and relaxation at L.A. Hotel & Spa, the premier destination in the heart of Addis Ababa.",
    exploreBtn: "Discover More",
    facilitiesTitle: "Exquisite Offerings",
    gymDesc: "State-of-the-art TechnoGym equipment with personalized trainers available to guide your journey.",
    spaDesc: "Ancient Ethiopian rituals combined with modern therapies for ultimate rejuvenation.",
    poolDesc: "Infinity pool overlooking the city skyline, heated for your year-round comfort.",
    membershipTitle: "Elevated Memberships",
    standardPlan: "Standard Wellness",
    premiumPlan: "Executive Fitness",
    elitePlan: "Diamond Elite",
    contactTitle: "Inquire for Membership",
    footerRights: "© 2025 L.A. Hotel & Spa. All rights reserved."
  },
  am: {
    navHome: "መነሻ",
    navAbout: "ስለ እኛ",
    navRooms: "ክፍሎች",
    navDining: "ምግብ ቤቶች እና ላውንጅ",
    navSpa: "ስፓ እና ማሳጅ",
    navFitness: "ሰውነት ማጎልመሻ",
    heroTitle: "ግርማ ሞገስ ያለው እንቅስቃሴ፣ ጤናማ መንፈስ",
    heroSub: "በአዲስ አበባ እምብርት በሚገኘው የኤል.ኤ ሆቴል እና ስፓ ከፍተኛውን የቅንጦት እና እረፍት ይለማመዱ።",
    exploreBtn: "የበለጠ ይወቁ",
    facilitiesTitle: "ድንቅ አገልግሎቶች",
    gymDesc: "ዘመናዊ የቴክኖጂም መሳሪያዎች ከግል አሰልጣኞች ጋር ለእርስዎ ተዘጋጅተዋል።",
    spaDesc: "ጥንታዊ የኢትዮጵያ ስርአቶች ከዘመናዊ ህክምናዎች ጋር ለላቀ እድሳት።",
    poolDesc: "የከተማዋን ገጽታ የሚመለከት ኢንፊኒቲ ገንዳ፣ ለዓመቱ ሙሉ ምቾት የሚሞቅ።",
    membershipTitle: "ከፍተኛ የአባልነት አማራጮች",
    standardPlan: "መደበኛ ጤና",
    premiumPlan: "ኤክስኪውቲቭ ብቃት",
    elitePlan: "ዳይመንድ ኢሊት",
    contactTitle: "ለአባልነት ይጠይቁ",
    footerRights: "© 2025 ኤል.ኤ ሆቴል እና ስፓ። መብቱ በህግ የተጠበቀ ነው።"
  },
  zh: {
    navHome: "首页",
    navAbout: "关于我们",
    navRooms: "客房",
    navDining: "餐厅与酒廊",
    navSpa: "水疗与按摩",
    navFitness: "健身",
    heroTitle: "律动优雅，身心康宁",
    heroSub: "在亚的斯亚贝巴核心地带的 L.A. 酒店及水疗中心体验巅峰健身与放松。",
    exploreBtn: "探索更多",
    facilitiesTitle: "精致设施",
    gymDesc: "最先进的泰诺健设备，提供私人教练为您指导。",
    spaDesc: "古老的埃塞俄比亚仪式与现代疗法相结合，实现终极焕活。",
    poolDesc: "俯瞰城市天际线的无边泳池，全年恒温。 ",
    membershipTitle: "高级会员",
    standardPlan: "标准康养",
    premiumPlan: "行政健身",
    elitePlan: "钻石精英",
    contactTitle: "咨询会员",
    footerRights: "© 2025 L.A. Hotel & Spa。保留所有权利。"
  },
  ar: {
    navHome: "الرئيسية",
    navAbout: "عن الفندق",
    navRooms: "الغرف",
    navDining: "المطاعم واللاونج",
    navSpa: "السبا والمساج",
    navFitness: "اللياقة البدنية",
    heroTitle: "أناقة في الحركة، عافية في الروح",
    heroSub: "اختبر قمة الفخامة والاسترخاء في فندق ومنتجع إل أيه بقلب أديس أبابا.",
    exploreBtn: "اكتشف المزيد",
    facilitiesTitle: "مرافق رائعة",
    gymDesc: "أحدث أجهزة تكنوجيم مع مدربين شخصيين متاحين لتوجيه رحلتك.",
    spaDesc: "طقوس إثيوبية قديمة مدمجة مع علاجات حديثة لتجديد شبابك في نهاية المطاف.",
    poolDesc: "مسبح إنفينيتي يطل على أفق المدينة، مدفأ لراحتك طوال العام.",
    membershipTitle: "عضويات متميزة",
    standardPlan: "العافية القياسية",
    premiumPlan: "اللياقة التنفيذية",
    elitePlan: "الماسية النخبة",
    contactTitle: "استفسر عن العضوية",
    footerRights: "© 2025 فندق ومنتجع إل أيه. جميع الحقوق محفوظة."
  },
  fr: {
    navHome: "Accueil",
    navAbout: "À Propos",
    navRooms: "Chambres",
    navDining: "Restaurants & Lounge",
    navSpa: "Spa & Massage",
    navFitness: "Fitness",
    heroTitle: "Élégance en Mouvement, Bien-être en Esprit",
    heroSub: "Vivez le summum du luxe et de la relaxation au L.A. Hotel & Spa, la destination phare au cœur d'Addis-Abeba.",
    exploreBtn: "Découvrir Plus",
    facilitiesTitle: "Offres Exquises",
    gymDesc: "Équipement TechnoGym de pointe avec des entraîneurs personnels disponibles pour vous guider.",
    spaDesc: "Rituels éthiopiens ancestraux combinés à des thérapies modernes pour un rajeunissement ultime.",
    poolDesc: "Piscine à débordement surplombant la ville, chauffée pour votre confort toute l'année.",
    membershipTitle: "Adhésions de Prestige",
    standardPlan: "Bien-être Standard",
    premiumPlan: "Fitness Exécutif",
    elitePlan: "Diamond Élite",
    contactTitle: "S'informer sur l'adhésion",
    footerRights: "© 2025 L.A. Hotel & Spa. Tous droits réservés."
  }
};
